//LOGIN
export const LOGIN_OAUTH = 'LOGIN_OAUTH';
export const LOGIN_MANUAL = 'LOGIN_MANUAL';
export const ERROR_GENERATED = 'ERROR_GENERATED';

//REGISTER
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_STEP_ONE = 'REGISTER_STEP_ONE';
export const REGISTER_STEP_TWO = 'REGISTER_STEP_TWO';
export const REGISTER_STEP_THREE = 'REGISTER_STEP_THREE';
export const REGISTER_STEP_FOUR = 'REGISTER_STEP_FOUR';