//LOGIN
export const LOGIN_OAUTH = 'LOGIN_OAUTH';
export const LOGIN_MANUAL = 'LOGIN_MANUAL';

//REGISTER
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_STEP_ONE = 'REGISTER_STEP_ONE';
export const REGISTER_STEP_TWO = 'REGISTER_STEP_TWO';
export const REGISTER_STEP_THREE = 'REGISTER_STEP_THREE';
export const REGISTER_STEP_FOUR = 'REGISTER_STEP_FOUR';
export const POST_SIP_AHLI = 'POST_SIP_AHLI';
export const GET_ID_TOKEN = 'GET_ID_TOKEN';


// THREADS
export const GET_THREADS = 'GET_THREADS';
export const POST_THREDS = 'POST_THREDS';
export const SEARCH_THREADS = 'SEARCH_THREADS';
