//LOGIN
export const LOGIN_OAUTH = 'LOGIN_OAUTH';
export const LOGIN_MANUAL = 'LOGIN_MANUAL';

export const USER_LOGOUT = 'USER_LOGOUT';

//REGISTER
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_STEP_ONE = 'REGISTER_STEP_ONE';
export const REGISTER_STEP_TWO = 'REGISTER_STEP_TWO';
export const REGISTER_STEP_THREE = 'REGISTER_STEP_THREE';
export const REGISTER_STEP_FOUR = 'REGISTER_STEP_FOUR';
export const POST_SIP_AHLI = 'POST_SIP_AHLI';
export const GET_ID_TOKEN = 'GET_ID_TOKEN';

// THREADS
export const GET_THREADS_STATIC = 'GET_THREADS_STATIC';
export const GET_THREADS = 'GET_THREADS';
export const POST_THREDS = 'POST_THREDS';
export const SEARCH_THREADS = 'SEARCH_THREADS';
export const REPORT_THREAD = 'REPORT_THREAD';
export const BOOKMARK_THREAD = 'BOOKMARK_THREAD';

//ON BOARDING
export const GET_ON_BOARDING = 'GET_ON_BOARDING';

// GET PROFILE / CURRENT USER
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

// INNER CIRCLE
export const GET_LIST_INNER_CIRCLE = 'GET_LIST_INNER_CIRCLE';
export const POST_INNER_CIRCLE = 'POST_INNER_CIRCLE';
export const PUT_INNER_CIRCLE = 'PUT_INNER_CIRCLE';
