# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TemanDiabetes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
    pod 'RNShare', :path => '../node_modules/react-native-share'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
