# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TemanDiabets' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'Firebase/Core', '~> 5.3.0'
    pod 'Firebase/Auth', '~> 5.3.0'
    pod 'Firebase/Messaging', '~> 5.3.0'
    pod 'Firebase/Storage', '~> 5.3.0'

  # pod for google signin
    pod 'GoogleSignIn'
    pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'
end
